before_script:
  - docker info
  - docker -v
  - docker-compose -v

job:
  script:
    - ./do telethon init debug skip_frontend
    - chmod o+w backend # needed to let the system create files with test coverage

    - ./do telethon restart debug skip_frontend
    - ./do telethon test_backend debug skip_frontend

  only:
    - NO_ONE
