---
project:
  title: NIG Repository
  description: platform for genomic and phenotypic datasets
  version: "1.1.2"
  rapydo: "2.4"

variables:
  roles:
    staff_user: disabled

  submodules:
    quality-checks:
      online_url: https://github.com/JuanMataNaranjo/CINECA_repo
      branch: main

  env:
    CHUNKS_LIMIT: 16
    CRONTAB_ENABLE: 1
    DATA_PATH: /data

    BACKEND_BUILD_MODE: backend-legacy39
    PYTHON_PATH: /usr/local/lib/python3.9/dist-packages
    FRONTEND_FRAMEWORK: angular
    AUTH_SERVICE: neo4j

    ACTIVATE_NEO4J: 1
    ACTIVATE_REDIS: 1
    ACTIVATE_CELERY: 1
    # ACTIVATE_FLOWER: 1
    CELERY_ENABLE_CONNECTOR: 1

    # 6 hours
    AUTH_JWT_TOKEN_TTL: 21600
    # 24 hours
    # AUTH_JWT_TOKEN_TTL: 86400
    # temporary raised to 1 month to ease the upload of the archives
    # AUTH_JWT_TOKEN_TTL: 2592000
    AUTH_FORCE_FIRST_PASSWORD_CHANGE: 1
    AUTH_MAX_PASSWORD_VALIDITY: 60
    AUTH_MIN_PASSWORD_LENGTH: 10
    AUTH_DISABLE_UNUSED_CREDENTIALS_AFTER: 180
    AUTH_MAX_LOGIN_ATTEMPTS: 3
    AUTH_SECOND_FACTOR_AUTHENTICATION: 1
    AUTH_TOKEN_IP_GRACE_PERIOD: 60
    ALLOW_PASSWORD_RESET: 1
    SSL_VERIFY_CLIENT: 1

tags:
  study: Manage information at study level
  dataset: Manage information at dataset level
  file: Manage files and resource files
  admin: Operations only allowed for admin users
  miscellaneous: Endpoints not classified in other specific sections
  phenotype: Manage phenotypes
  technicals: Manage set of technical metadata
