
# per invio a Qradar

$template Formato-nginx, "<%pri%>1 %TIMESTAMP:::date-rfc3339% nig_proxy.nginx %syslogtag%%msg:::sp-if-no-1st-sp%%msg::drop-last-lf%\n"
$template Formato-nginx-error, "<%pri%>1 %TIMESTAMP:::date-rfc3339% nig_proxy.nginx httpd-error:%msg:::sp-if-no-1st-sp%%msg::drop-last-lf%\n"


input(type="imfile"
      File="/var/log/nginx/error.log"
      Tag="httpd-error")

:programname,isequal,"httpd" @qradar-collector.private.cineca.it;Formato-nginx
:programname,isequal,"httpd-error" @qradar-collector.private.cineca.it;Formato-nginx-error

#Evita che i log vengano processati ulteriormente

:syslogtag,startswith,"http" stop
