version: "3.8"

services:
  backend:
    build: ${PROJECT_DIR}/builds/backend
    image: nig/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/data:/data
      - ${DATA_DIR}/resources:/resources
      - ${PROJECT_DIR}/backend/snakemake:/snakemake

  celery:
    build: ${PROJECT_DIR}/builds/backend
    image: nig/backend:${RAPYDO_VERSION}
    volumes:
      - ${DATA_DIR}/data:/data
      - ${DATA_DIR}/resources:/resources
      - ${PROJECT_DIR}/backend/snakemake:/snakemake

  neo4j:
    volumes:
      - ${DATA_DIR}/graphdata:/data
      - ${DATA_DIR}/data:/var/lib/neo4j/import/repo
    ports:
      - 7687:7687
      - 9090:${NEO4J_WEB_INTERFACE_PORT}
