version: "3"

services:
  backend:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: nig/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/data:/data
      - ${VANILLA_DIR}/data/resources:/resources

  celery:
    build: ${VANILLA_DIR}/projects/${COMPOSE_PROJECT_NAME}/builds/backend
    image: nig/backend:${RAPYDO_VERSION}
    volumes:
      - ${VANILLA_DIR}/data/data:/data
      - ${VANILLA_DIR}/data/resources:/resources

  neo4j:
    volumes:
      - ${VANILLA_DIR}/data/graphdata:/data
      - ${VANILLA_DIR}/data/data:/var/lib/neo4j/import/repo
    ports:
      - 7687:7687
      - 9090:${NEO4J_WEB_INTERFACE_PORT}
    # environment:
    #   NEO4J_dbms_memory_pagecache_size: 512M
    #   NEO4J_dbms_memory_heap_maxSize: 1024M
