version: "3.9"

services:
  backend:
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  neo4j:
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  redis:
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  rabbit:
    deploy:
      placement:
        constraints:
          - "node.role==manager"
