version: "3.9"

services:
  backend:
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  celery:
    deploy:
      mode: global
      placement:
        constraints:
          - "node.role==worker"

  neo4j:
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  redis:
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  rabbit:
    deploy:
      placement:
        constraints:
          - "node.role==manager"

  frontend:
    deploy:
      placement:
        constraints:
          - "node.role==manager"
