name: Frontend

on:
  push:
  # schedule:
  #   - cron: "0 5 * * *"
  workflow_dispatch:
env:
  PROJECT: nig

jobs:
  frontend-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: rapydo/actions/install@v1
        with:
          project: ${PROJECT}
          swarm: 1

      - name: Run Karma
        run: |
          rapydo pull --quiet frontend
          rapydo start frontend
          sleep 5
          rapydo logs frontend
          rapydo shell frontend "yarn install"
          rapydo shell frontend "reload-types"
          rapydo shell frontend "yarn run test:single"

      - name: Coverage
        uses: rapydo/actions/coverage@v1
        with:
          repository: projects/${PROJECT}
          project: ${PROJECT}
          step: frontend

      - name: Production Mode
        run: |
          rapydo remove
          rapydo --testing --prod init --force
          rapydo password registry --random
          rapydo pull --quiet frontend proxy

          rapydo start frontend proxy
          # In swarm mode --follow no longer stop when the container exits
          # rapydo logs --follow frontend
          sleep 300
          rapydo logs --tail 20 proxy
          rapydo logs --tail 20 frontend
          rapydo logs --tail 6 frontend | grep "files have been compressed."
          curl --insecure -X GET https://localhost
