name: MyPy

env:
  PROJECT: nig

on:
  push:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: rapydo/actions/mypy@v2
        with:
          project: ${PROJECT}
          install: pronto typer pandas-stubs types-pyOpenSSL
          ignore: vcf snakemake
