name: MyPy

env:
  PROJECT: nig

on:
  push:
  workflow_dispatch:

jobs:
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - uses: rapydo/actions/install@v2
        with:
          project: ${PROJECT}
          submodule: http-api
      - uses: rapydo/actions/mypy@v2
        with:
          project: ${PROJECT}
          install: pronto typer pandas-stubs types-pyOpenSSL
          ignore: vcf snakemake
      - name: Save Report
        uses: actions/upload-artifact@v2
        with:
          name: mypy-report
          path: report
